name: Say Hello

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Mensaje
        run: echo "Hola de nuevo"
